export type ColorMode = "light" | "dark";
export type AppLocale = "zh-TW" | "en";

export type AppPreferences = {
  colorMode: ColorMode;
  locale: AppLocale;
  defaultPresentationLanguage: string;
  defaultSlideCount: string;
};

export const preferencesStorageKey = "ppt-creator-preferences";

export const defaultPreferences: AppPreferences = {
  colorMode: "light",
  locale: "zh-TW",
  defaultPresentationLanguage: "zh-TW",
  defaultSlideCount: "10",
};

export function normalizePreferences(value: unknown): AppPreferences {
  if (!value || typeof value !== "object") return defaultPreferences;
  const candidate = value as Partial<AppPreferences>;
  return {
    colorMode: candidate.colorMode === "dark" ? "dark" : "light",
    locale: candidate.locale === "en" ? "en" : "zh-TW",
    defaultPresentationLanguage: ["zh-TW", "en", "ja"].includes(candidate.defaultPresentationLanguage ?? "")
      ? candidate.defaultPresentationLanguage!
      : defaultPreferences.defaultPresentationLanguage,
    defaultSlideCount: ["6", "10", "15", "20"].includes(candidate.defaultSlideCount ?? "")
      ? candidate.defaultSlideCount!
      : defaultPreferences.defaultSlideCount,
  };
}

export function readPreferences(storage: Pick<Storage, "getItem">): AppPreferences {
  try {
    const saved = storage.getItem(preferencesStorageKey);
    return saved ? normalizePreferences(JSON.parse(saved)) : defaultPreferences;
  } catch {
    return defaultPreferences;
  }
}

export function writePreferences(storage: Pick<Storage, "setItem">, preferences: AppPreferences): void {
  storage.setItem(preferencesStorageKey, JSON.stringify(normalizePreferences(preferences)));
}

const english: Record<string, string> = {
  "建立簡報": "Create",
  "我的簡報": "My decks",
  "任務中心": "Jobs",
  "設定": "Settings",
  "主要導覽（已收合）": "Main navigation (collapsed)",
  "主要導覽": "Main navigation",
  "使用說明": "Help",
  "搜尋": "Search",
  "新增簡報": "New deck",
  "使用者選單": "User menu",
  "AI 簡報工作室": "AI PRESENTATION STUDIO",
  "讓每個想法": "Make every idea",
  "都值得被看見": "worth presenting",
  "輸入主題或加入參考資料，我們會先整理架構，再讓你逐頁確認完整成果。": "Enter a topic or add source files. We will shape the story first, then let you review every slide.",
  "產品特點": "Product highlights",
  "可編輯 PPTX": "Editable PPTX",
  "下載前完整預覽": "Full preview before download",
  "支援本地模型": "Local models supported",
  "告訴我們簡報要說什麼": "Tell us what your presentation should say",
  "簡報主題與需求": "Topic and requirements",
  "例如：為管理團隊製作一份 2026 年產品策略提案，重點放在市場機會、三項優先計畫與執行時程。": "Example: Create a 2026 product strategy proposal for the leadership team, focusing on market opportunities, three priorities, and the execution timeline.",
  "參考資料": "Source files",
  "選填，最多 8 個檔案": "Optional, up to 8 files",
  "選擇參考檔案": "Choose source files",
  "拖曳檔案到這裡": "Drop files here",
  "或點擊選擇 PDF、PPTX、TXT": "or choose PDF, PPTX, or TXT",
  "已加入的檔案": "Added files",
  "解析失敗": "Parsing failed",
  "簡報語言": "Presentation language",
  "繁體中文": "Traditional Chinese",
  "預計頁數": "Estimated length",
  "約 6 頁": "About 6 slides",
  "約 10 頁": "About 10 slides",
  "約 15 頁": "About 15 slides",
  "約 20 頁": "About 20 slides",
  "自訂頁數": "Custom length",
  "頁": "slides",
  "使用的 AI 模型": "AI model",
  "請先到設定新增 AI API": "Add an AI API in Settings first",
  "可在設定中加入更多本機或雲端模型 API。": "Add more local or cloud model APIs in Settings.",
  "在簡報中生成圖片": "Generate images for the deck",
  "優先使用本機圖片 API，最多生成 2 張，避免雲端費用。": "Prefer local image APIs and generate up to 2 images to limit cloud costs.",
  "圖片生成模型": "Image model",
  "請選擇圖片模型": "Choose an image model",
  "本機免額度": "Local · no quota",
  "本機生成・免雲端額度": "Local generation · no cloud credits",
  "雲端可能計費": "Cloud usage may be billed",
  "請先到設定新增本機 Stable Diffusion API。": "Add a local Stable Diffusion API in Settings first.",
  "選擇視覺風格": "Choose a visual style",
  "先產生簡報大綱": "Generate outline first",
  "先在網站完整確認每一頁，確認後才會開放下載。": "Review every slide here before downloads are enabled.",
  "正在製作你的簡報": "CREATING YOUR PRESENTATION",
  "無法完成這次生成": "We could not complete this generation",
  "把內容變成清楚的故事": "Turning your content into a clear story",
  "AI 服務正在整理重點、安排順序，並為每一頁選擇合適的版面。": "The AI is organizing key points, sequencing the story, and choosing a suitable layout for each slide.",
  "請檢查本機服務": "Check local services",
  "等待背景任務": "Waiting for the background job",
  "請確認後端 API 與 AI 服務都已啟動": "Make sure the backend API and AI service are running",
  "返回設定": "Back to setup",
  "取消這次生成": "Cancel generation",
  "參考資料解析結果": "Source parsing results",
  "預估剩餘時間": "Estimated time remaining",
  "預估剩餘": "ETA",
  "已經過時間": "Elapsed time",
  "正在計算": "Calculating",
  "時間會依模型、頁數與硬體速度動態調整，任務結束後會自動釋放本機模型資源": "Timing adjusts to the model, slide count, and hardware speed. Local model resources are released automatically when the job ends",
  "等待背景工作程序": "Waiting for the background worker",
  "任務已恢復，等待繼續": "Job restored and waiting to continue",
  "已恢復，等待繼續": "Restored and waiting to continue",
  "正在啟動本機模型": "Starting the local model",
  "正在啟動模型": "Starting the model",
  "正在分析資料並規劃大綱": "Analyzing sources and planning the outline",
  "正在規劃簡報大綱": "Planning the presentation outline",
  "正在儲存簡報大綱": "Saving the presentation outline",
  "大綱已完成": "Outline complete",
  "簡報大綱已完成": "Presentation outline complete",
  "正在準備逐頁內容": "Preparing slide content",
  "正在產生逐頁內容": "Generating slide content",
  "正在分批產生逐頁內容": "Generating slide content in batches",
  "部分內容未通過驗證，正在重試": "Some content failed validation and is being retried",
  "正在儲存逐頁內容": "Saving slide content",
  "逐頁內容已完成": "Slide content complete",
  "正在取消並釋放模型": "Canceling and releasing models",
  "正在取消任務": "Canceling job",
  "任務已取消": "Job canceled",
  "正在準備參考資料": "Preparing source files",
  "正在準備正式預覽": "Preparing the final preview",
  "正在渲染正式預覽": "Rendering the final preview",
  "預估少於 30 秒": "Estimated under 30 sec",
  "連線暫時中斷，正在自動重新連線": "Connection interrupted; reconnecting automatically",
  "分析內容與參考資料": "Analyze content and source files",
  "整理簡報敘事架構": "Shape the presentation narrative",
  "建立逐頁內容": "Create slide content",
  "套用版型並檢查版面": "Apply layouts and check composition",
  "生成前確認": "REVIEW BEFORE GENERATION",
  "先把故事架構排好": "Shape the story before building the slides",
  "調整標題、順序與每頁目的，確認後才會生成完整內容。": "Adjust titles, order, and each slide's purpose. Full content is generated after confirmation.",
  "頁簡報": "slides",
  "簡報名稱": "Presentation title",
  "簡報大綱": "Presentation outline",
  "眉標": "Eyebrow",
  "頁型": "Layout",
  "頁面標題": "Slide title",
  "這一頁要傳達什麼": "What should this slide communicate?",
  "新增內容頁": "Add content slide",
  "正在建立任務": "Creating job",
  "確認大綱並生成內容": "Confirm outline and generate content",
  "返回建立頁": "Back to create",
  "封面": "Cover",
  "章節轉場": "Section divider",
  "重點卡片": "Key-point cards",
  "左右圖文": "Split layout",
  "數據焦點": "Metric focus",
  "雙欄比較": "Two-column comparison",
  "執行路徑": "Roadmap",
  "關鍵引言": "Key quote",
  "結尾": "Closing",
  "返回預覽": "Back to preview",
  "簡報編輯工作台": "Presentation editor",
  "有未儲存修改": "Unsaved changes",
  "內容已儲存": "Changes saved",
  "版本紀錄": "Version history",
  "正在更新預覽": "Updating preview",
  "儲存並更新預覽": "Save and update preview",
  "可編輯投影片列表": "Editable slide list",
  "投影片": "Slides",
  "新增投影片": "Add slide",
  "即時內容預覽": "Live content preview",
  "編輯投影片內容": "Edit slide content",
  "向前移動": "Move earlier",
  "向後移動": "Move later",
  "頁面類型": "Slide type",
  "標題": "Title",
  "內文": "Body",
  "卡片內容": "Card content",
  "階段內容": "Stage content",
  "這些欄位會直接呈現在版型中": "These fields appear directly in the layout",
  "項目": "Item",
  "標籤": "Label",
  "小標題": "Subtitle",
  "說明": "Description",
  "數據內容": "Metric content",
  "數值必須來自可信資料": "Metrics must come from a reliable source",
  "主要數值": "Primary metric",
  "數值標籤": "Metric label",
  "補充脈絡": "Supporting context",
  "比較內容": "Comparison content",
  "左右欄與最後結論": "Left and right columns plus a conclusion",
  "左欄": "Left column",
  "右欄": "Right column",
  "欄位標題": "Column title",
  "內容": "Content",
  "比較結論": "Comparison conclusion",
  "移除這頁圖片": "Remove slide image",
  "複製此頁": "Duplicate slide",
  "刪除此頁": "Delete slide",
  "文字修改與排序不會呼叫 AI。儲存後才會重新產生正式 PPTX、PDF 與逐頁預覽。": "Editing and reordering do not call AI. Saving regenerates the PPTX, PDF, and slide previews.",
  "查看過去內容，還原時不會覆蓋原有版本。": "Review previous content. Restoring creates a new version without overwriting history.",
  "關閉版本紀錄": "Close version history",
  "正在讀取版本…": "Loading versions…",
  "目前還沒有版本紀錄。": "No version history yet.",
  "版本": "Version",
  "正在還原": "Restoring",
  "還原此版本": "Restore this version",
  "選擇版本以查看內容。": "Choose a version to preview its content.",
  "返回修改": "Back to edit",
  "未命名簡報": "Untitled presentation",
  "已完成預覽": "Preview ready",
  "切換簡報模板": "Change presentation template",
  "切換網站進場動畫與 PPTX 淡入轉場": "Toggle website entrance animation and PPTX fade transitions",
  "動畫已開啟": "Animations on",
  "加入動畫": "Add animations",
  "退出全螢幕": "Exit full screen",
  "全螢幕預覽": "Full-screen preview",
  "下載 PDF": "Download PDF",
  "下載 PPTX": "Download PPTX",
  "確認後下載": "Confirm to download",
  "投影片縮圖": "Slide thumbnails",
  "正式輸出": "Final output",
  "正式 PPTX / PDF 渲染": "Final PPTX / PDF rendering",
  "正在重新套用模板": "Applying template again",
  "上一頁": "Previous slide",
  "下一頁": "Next slide",
  "下載前確認": "REVIEW BEFORE DOWNLOAD",
  "每一頁都看過了嗎？": "Have you reviewed every slide?",
  "請檢查文字、數字與版面。若需要修改，可以返回上一步重新產生。": "Check the copy, numbers, and layout. Return to editing if anything needs adjustment.",
  "標題與內容正確": "Titles and content are correct",
  "沒有文字溢出": "No text overflow",
  "預覽與下載檔一致": "Preview matches the downloaded file",
  "確認簡報沒問題": "Confirm presentation",
  "已確認，可以下載": "Confirmed and ready to download",
  "PPTX 內的文字仍可編輯": "Text remains editable in PPTX",
  "需要調整內容": "Edit content",
  "工作空間": "WORKSPACE",
  "查看、預覽與管理你建立的所有簡報。": "View, preview, and manage all your presentations.",
  "搜尋簡報": "Search presentations",
  "最近更新": "Recently updated",
  "批次刪除": "Delete selected",
  "正在讀取簡報…": "Loading presentations…",
  "草稿": "Draft",
  "解析中": "Parsing",
  "生成中": "Generating",
  "渲染中": "Rendering",
  "待確認": "Awaiting review",
  "已完成": "Completed",
  "失敗": "Failed",
  "重試中": "Retrying",
  "重新渲染": "Render again",
  "重試": "Retry",
  "開啟": "Open",
  "複製": "Duplicate",
  "找不到符合的簡報": "No matching presentations",
  "還沒有簡報": "No presentations yet",
  "請試試其他關鍵字。": "Try another search term.",
  "完成第一次生成後，簡報會自動保存在這裡。": "Your presentations will be saved here after the first generation.",
  "建立新簡報": "Create a new presentation",
  "從主題或文件開始": "Start from a topic or document",
  "生成任務中心": "Generation jobs",
  "查看所有背景任務，重新接回進度或處理失敗項目。": "Review background jobs, resume progress, or handle failed items.",
  "重新整理": "Refresh",
  "任務狀態篩選": "Filter jobs by status",
  "全部": "All",
  "執行中": "Active",
  "已取消": "Canceled",
  "等待中": "Queued",
  "正在讀取任務…": "Loading jobs…",
  "目前沒有這個狀態的任務": "No jobs with this status",
  "建立簡報後，生成進度會出現在這裡。": "Generation progress will appear here after you create a presentation.",
  "生成任務列表": "Generation jobs",
  "大綱生成": "Outline",
  "內容生成": "Content",
  "查看進度": "View progress",
  "開啟目前簡報": "Open presentation",
  "已由後續任務處理": "Handled by a later job",
  "偏好設定": "PREFERENCES",
  "AI 模型設定": "AI model settings",
  "加入文字與本機圖片模型 API，測試後可在建立簡報時自由選擇。": "Connect text and local image model APIs, test them, and choose freely when creating a presentation.",
  "介面與外觀": "Interface & appearance",
  "調整網站語言與色彩模式，設定會自動保存在這台裝置。": "Choose the interface language and color mode. Preferences are saved on this device.",
  "介面語言": "Interface language",
  "只會切換網站操作文字，不會翻譯既有簡報內容。": "Changes website controls only; existing presentation content is not translated.",
  "外觀模式": "Appearance",
  "淺色": "Light",
  "深色": "Dark",
  "淺色模式": "Light mode",
  "深色模式": "Dark mode",
  "已串接的 AI 模型": "Connected AI models",
  "API Key 會加密保存，設定頁不會再次顯示明文。": "API keys are encrypted and never shown again on this page.",
  "新增模型": "Add model",
  "設定名稱": "Connection name",
  "例如：公司 OpenAI": "Example: Company OpenAI",
  "API 類型": "API type",
  "本機模型／Checkpoint": "Local model / checkpoint",
  "模型名稱": "Model name",
  "輸入 API 提供的模型 ID": "Enter the model ID from your provider",
  "專用圖片模型（選填）": "Dedicated image model (optional)",
  "留空時會嘗試使用文字模型的圖片生成工具。": "Leave blank to try the text model's image tool.",
  "相容 API 需填寫可用的圖片模型。": "Compatible APIs require an available image model.",
  "選填": "optional",
  "取消": "Cancel",
  "儲存中": "Saving",
  "儲存設定": "Save settings",
  "尚未測試": "Not tested",
  "測試中": "Testing",
  "已連線": "Connected",
  "連線失敗": "Connection failed",
  "圖片模型": "Image model",
  "系統預設": "System default",
  "本機生成，不使用雲端額度": "Local generation · no cloud credits",
  "API Key 已加密保存": "API key encrypted",
  "未設定 API Key": "No API key",
  "測試": "Test",
  "目前無法讀取 AI API，請確認後端服務與 PostgreSQL 已啟動。": "AI APIs are unavailable. Make sure the backend and PostgreSQL are running.",
  "簡報預設值": "Presentation defaults",
  "建立新簡報時會自動帶入以下設定。": "These values are applied whenever you start a new presentation.",
  "預設語言": "Default language",
  "預設頁數": "Default slide count",
  "本機 API": "Local API",
  "OpenAI 相容 API": "OpenAI-compatible API",
  "本機 Stable Diffusion": "Local Stable Diffusion",
  "本機預設": "Local default",
  "創意編輯": "Creative Editorial",
  "桃紅撞色與大膽編排": "Bold composition with vivid pink accents",
  "深夜科技": "Midnight Tech",
  "深色高對比的科技質感": "High-contrast dark technology aesthetic",
  "紙本報告": "Paper Report",
  "襯線字與溫暖紙張色調": "Serif typography and warm paper tones",
  "海洋策略": "Ocean Strategy",
  "冷靜藍綠的專業提案": "Calm teal tones for professional proposals",
  "永續森林": "Sustainable Forest",
  "自然綠與有機曲線": "Natural greens and organic curves",
  "熾熱發表": "Ember Pitch",
  "橘紅能量與斜向光束": "Orange energy and diagonal beams",
  "柔霧創意": "Lavender Haze",
  "紫色柔光的優雅敘事": "Elegant storytelling with soft violet light",
  "瑞士藍圖": "Swiss Blueprint",
  "網格系統與精準藍色": "A precise blue grid system",
  "黑白極簡": "Monochrome",
  "純粹留白與銳利線條": "Crisp lines and disciplined whitespace",
  "極光未來": "Aurora Future",
  "霓虹漸層與未來氛圍": "Neon gradients and a futuristic atmosphere",
};

export function translate(locale: AppLocale, text: string): string {
  return locale === "en" ? english[text] ?? text : text;
}
